[versions]
agp = "8.7.3"
kotlin = "2.1.0"
minSdk = "21"
targetSdk = "35"
compileSdk = "35"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }

[plugins]
android-library      = { id = "com.android.library",      version.ref = "agp" }
android-application  = { id = "com.android.application",  version.ref = "agp" }
kotlin-android       = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
